# Linear Regression Implementation

In [111]:
import numpy as np
np.random.seed(0)

X is the independent variable, whereas Y is the dependent variable. Weights are the constants that X will be multiplied with to obtain Y. <br> Mathematical Equation : $ Y = w_1x_1 + w_2x_2 + ... + w_nx_n + w_0 $ <br> Vector form: $ Wx = Y $

In [75]:
X = np.array([[1, 2], [1, 1], [2, 1], [1, 3], [4, 1], [4, 6]])
Y = np.array([[20],[14],[19],[26], [29], [59]])
weights = np.random.rand(3,1)

When we have multiple data points as in multiple rows corresponding to an individual Y generated from the same set of W, we maintain their count using $m$ and the number of independent variable in an equation or the number of attributes using $n$, hence X is a matrix of $m * n$. To maintain $w_0$, we add a column with ones, hence size of X matrix is $n+1$, and the weight matrix is a matrix of $(n + 1) * 1$. The Y matrix is of shape $m * 1$.

General form : XW = Y <br>
\begin{bmatrix}
x^1_1 & x^1_2 & ... & x^1_n & 1\\
x^2_1 & x^2_2 & ... & x^2_n & 1\\ 
... & ... & ... & ... & ...\\ 
x^m_1 & x^m_2 & ... & x^m_n & 1
\end{bmatrix} \begin{bmatrix}
w_1\\ 
w_2\\ 
...\\ 
w_n\\
w_0
\end{bmatrix}
\begin{bmatrix}
y_1\\ 
y_2\\ 
...\\ 
y_m\\
\end{bmatrix}

In [76]:
print(X, Y, weights, end = "\n")

[[1 2]
 [1 1]
 [2 1]
 [1 3]
 [4 1]
 [4 6]] [[20]
 [14]
 [19]
 [26]
 [29]
 [59]] [[0.32932027]
 [0.22565347]
 [0.66598187]]


In [77]:
print(X.shape, Y.shape, weights.shape, end="\n")

(6, 2) (6, 1) (3, 1)


In [78]:
# Adding the bias 
X = np.append(X, np.ones((6,1)), axis=1)
print(X)

[[1. 2. 1.]
 [1. 1. 1.]
 [2. 1. 1.]
 [1. 3. 1.]
 [4. 1. 1.]
 [4. 6. 1.]]


In [96]:
def gradient(X, Y, weights):
    diff = (X.dot(weights) - Y).T
    finalGradient = diff.dot(X)
    return finalGradient.T

def costFunction(weights, X, Y):
    cost = X.dot(weights) - Y
    costd = (1/(2*X.shape[0]))*np.sum(cost**2)
    return costd

def gradientDescent(X, Y, learningRate, epochs):
    global weights
    for i in range(epochs):
        gradientCalc = gradient(X, Y, weights)
        weights = weights - (1/X.shape[0])*learningRate*gradientCalc
        print(costFunction(weights, X, Y))
    return weights

In [106]:
newWeights = gradientDescent(X, Y, 0.01, 2000)

7.394907710273906e-15
7.361451356643364e-15
7.32814677868484e-15
7.294992474246027e-15
7.261988510061238e-15
7.22913396769144e-15
7.196427547694382e-15
7.163869606769258e-15
7.131458607628294e-15
7.099194284806049e-15
7.067076152481944e-15
7.0351031513821495e-15
7.003274942081829e-15
6.971590498745214e-15
6.940049485220241e-15
6.908651335986966e-15
6.877395030131404e-15
6.846280362652169e-15
6.815306079926903e-15
6.784472519012712e-15
6.753778181254927e-15
6.72322260845179e-15
6.6928052716379285e-15
6.662525527703886e-15
6.632383076785187e-15
6.602376527482082e-15
6.572506118446727e-15
6.542770748030901e-15
6.513169864999662e-15
6.483702765210726e-15
6.454368991327939e-15
6.425168247523786e-15
6.396099262919388e-15
6.3671621044253396e-15
6.338355723076566e-15
6.309679383165805e-15
6.281133135546527e-15
6.252716276123211e-15
6.224427579235706e-15
6.1962668880488675e-15
6.168233570065572e-15
6.140327134162926e-15
6.11254696716738e-15
6.0848923772276696e-15
6.057363276721117e-15
6.0299584

2.577792858232338e-17
2.566130756553107e-17
2.5545200624377754e-17
2.542963379016495e-17
2.5314588763014927e-17
2.5200045092259603e-17
2.5086051061553783e-17
2.4972561673066057e-17
2.485956759222874e-17
2.4747102145817612e-17
2.463513470980032e-17
2.452368598769117e-17
2.4412728327964843e-17
2.430228223677947e-17
2.4192341492524776e-17
2.408289612966531e-17
2.3973922785799792e-17
2.386546933982166e-17
2.3757492642981832e-17
2.3650004817761593e-17
2.3543007306613082e-17
2.3436490338048014e-17
2.3330465535505053e-17
2.3224915886787513e-17
2.3119836877396688e-17
2.3015242550880273e-17
2.2911120044839123e-17
2.2807453842253798e-17
2.2704274775298137e-17
2.260155173937071e-17
2.2499292671683084e-17
2.239750230352241e-17
2.2296185147343193e-17
2.2195311202097046e-17
2.209488577056614e-17
2.1994928996627653e-17
2.1895421408725837e-17
2.179635567885985e-17
2.1697741365601532e-17
2.1599575358430528e-17
2.1501858286039263e-17
2.1404576929113204e-17
2.130773765928031e-17
2.1211341878513906e-17
2.

9.583785587755304e-19
9.540434430830224e-19
9.497261451293527e-19
9.45430062132703e-19
9.411539794744711e-19
9.368970040365796e-19
9.326555949653166e-19
9.284366341946038e-19
9.242372940967029e-19
9.200550238123051e-19
9.158920477248486e-19
9.117489436791537e-19
9.07623718159026e-19
9.035177064653756e-19
8.994312488707246e-19
8.953599483072485e-19
8.91309735735733e-19
8.872778064945476e-19
8.832629034517977e-19
8.792679439581579e-19
8.75289697402081e-19
8.713302820457546e-19
8.673885811032653e-19
8.634630320407418e-19
8.595570571734491e-19
8.556654606495765e-19


array([[5.],
       [6.],
       [3.]])

In [107]:
print(newWeights)

[[5.]
 [6.]
 [3.]]


In [109]:
pred = X.dot(newWeights)
print(pred)

[[20.]
 [14.]
 [19.]
 [26.]
 [29.]
 [59.]]
